#!/bin/bash

source ./install_functions.sh

check_paru_install
install_preliminary_packages
install_required_packages
configure_hyprland
install_dev_packages
configure_dev_packages
configure_swww
stow_dotfiles
configure_fish
configure_sddm
configure_bluetooth
